### ISSUE TITLE
Collab

### ISSUE THREAD

**Issue by Great-error** [Mayo374/EchOS#2]
Ok let's discuss here

**Comment by Great-error** [comment]
so one thing is collaborating on a discord issues tab is very inefficient and sus
so I think you should consider making a discord acc

**Comment by Great-error** [comment]
and we should start with the bootloader obviously.. and I expect you have the usual stuff you know the vm and the other stuff

**Comment by Great-error** [comment]
right?

**Comment by Mayo374** [comment]
Ok im here

**Comment by Great-error** [comment]
so I have exams going on they end on Monday so until then progress might hinder but I think we can get a fully functional bootloader done by this month even if neither of us know anything

**Comment by Mayo374** [comment]
sounds good maybe making the hello world assembly file bootable

**Comment by Great-error** [comment]
yes exactly

**Comment by Great-error** [comment]
so what about the discord account then? it will be easier for us to work

**Comment by Mayo374** [comment]
For now I won't have a discord account until Maybe in the future

**Comment by Great-error** [comment]
alr sounds good to me... I have to study a bit and its night time where I'm at so it might take some time for me

**Comment by Great-error** [comment]
so you can get started with making the asm file bootable

**Comment by Great-error** [comment]
and after a while I'll test it and load in the other boot sectors

**Comment by Mayo374** [comment]
Wait what about instead focusing on the Cosmos project? I already have a functional working OS up and running. Maybe we could add features or something to it.

**Comment by Great-error** [comment]
comos isnt from scratch tho

**Comment by Great-error** [comment]
not saying it isnt a good idea
but idk man

**Comment by Mayo374** [comment]
I tried assembly and for me it's a pain in the head.

**Comment by Great-error** [comment]
I'm new to asm but I get a lot of it so I'll focus on the lower ends of this project

**Comment by Great-error** [comment]
if you dont mind that is

**Comment by Great-error** [comment]
for example asm and c... you can work in c# and c++

**Comment by Great-error** [comment]
but I have no idea about inno so youre going to have to do that

**Comment by Great-error** [comment]
looks like you know more than me though because you have already started to make os's

**Comment by Great-error** [comment]
are you there?

**Comment by Mayo374** [comment]
I still consider myself a beginner as i started a year ago

**Comment by Mayo374** [comment]
I think I'm going to stick to Cosmos Making an OS feels like it would be a pain.

**Comment by Great-error** [comment]
ohk I was looking to making an os fron scratch because cosmos seems very well done right?

**Comment by Great-error** [comment]
I dont feel like I'm learning anything

**Comment by Great-error** [comment]
but anyways your choice

**Comment by Mayo374** [comment]
Ahh it's about learning? I recommend finding a C# Course or your desired language of choice. then learning it and using it to make your own projects if you truly want to learn.

**Comment by Mayo374** [comment]
Assembly wouldn't be a good language because it requires a deeper understanding of how computers work (Unless that's what you want)

**Comment by Great-error** [comment]
it is what I want becuz I konw how computers work :'D

**Comment by Great-error** [comment]
so looks like this wont work out

**Comment by Great-error** [comment]
cuz like I want this to be open source and even if its simple It has to be my own

**Comment by Great-error** [comment]
I'll just close the thread then

**Comment by Mayo374** [comment]
Yeah, I'm very sorry. But If you want to know how computers work then assembly may be for you.

**Comment by Great-error** [comment]
...

**Comment by Great-error** [comment]
wish you the best of luck

**Comment by Great-error** [comment]
I'll stay in touch just in case yours and my view of things change

**Comment by audiotore482** [comment]
Hey Great error you still up for OS development?

**Comment by audiotore482** [comment]
My username is different because I just lost my account :/ but im porting EchOS from cosmos to scratch and im already 90% done so I didnt know if you still wanted help.

> I'll stay in touch just in case yours and my view of things change

**Comment by audiotore482** [comment]
I can help you work on your own OS. and I will explain everything to you
